spring.application.name=servepay-platform
spring.datasource.url=YOUR_DB_URL
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
razorpay.key.id=YOUR_KEY
razorpay.key.secret=YOUR_SECRET

